# Generated by Django 5.2.16 on 2026-07-31 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('qcm_batch', 'QCM (série complète)'), ('guided_exercise', 'Exercice guidé')], max_length=20)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], max_length=20)),
                ('question_count', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('tokens_used_on_generation', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.topic')),
            ],
            options={
                'verbose_name': 'Génération mise en cache',
                'verbose_name_plural': 'Générations mises en cache',
                'db_table': 'ai_engine_cached_generation',
            },
        ),
        migrations.CreateModel(
            name='QCMSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('qcm_batch', 'QCM (série complète)'), ('guided_exercise', 'Exercice guidé')], default='qcm_batch', max_length=20)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('served_from_cache', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score_percent', models.FloatField(blank=True, null=True)),
                ('cached_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='ai_engine.cachedgeneration')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de QCM',
                'verbose_name_plural': 'Sessions de QCM',
                'db_table': 'ai_engine_qcm_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_choice_key', models.CharField(max_length=4)),
                ('explanation', models.TextField(help_text='Correction détaillée étape par étape (Module 2 : Exercice & Correction Détaillée).')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai_engine.qcmsession')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'ai_engine_question',
                'ordering': ['session', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TutorConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='exams.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation avec le tuteur',
                'verbose_name_plural': 'Conversations avec le tuteur',
                'db_table': 'ai_engine_tutor_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Candidat'), ('assistant', 'Tuteur IA')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.tutorconversation')),
            ],
            options={
                'verbose_name': 'Message du tuteur',
                'verbose_name_plural': 'Messages du tuteur',
                'db_table': 'ai_engine_tutor_message',
                'ordering': ['conversation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice_key', models.CharField(max_length=4)),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='ai_engine.question')),
            ],
            options={
                'verbose_name': 'Réponse candidat',
                'verbose_name_plural': 'Réponses candidats',
                'db_table': 'ai_engine_user_answer',
            },
        ),
        migrations.AddIndex(
            model_name='cachedgeneration',
            index=models.Index(fields=['exam', 'subject', 'topic', 'difficulty'], name='ai_engine_c_exam_id_73c7c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('session', 'order')},
        ),
    ]
