# Generated by Django 5.2.16 on 2026-08-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="study_level",
            field=models.CharField(
                choices=[
                    ("cep", "CEP"),
                    ("bepc", "BEPC"),
                    ("bac", "Baccalauréat"),
                    ("licence", "Licence"),
                    ("master", "Master"),
                    ("autre", "Autre"),
                ],
                default="autre",
                max_length=20,
            ),
        ),
    ]
